name: Deploy Image to Amazon ECR (Dev)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Auth using App
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1193341
          private-key: ${{ vars.GH_APP_PRIVATE_KEY }}
