name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - preprod
      - production
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged # Required for Docker-in-Docker
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Fetch and checkout correct branch
        run: |
          echo "Fetching and checking out the correct branch..."
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            git fetch origin dev
            git checkout dev
          elif [ "${{ github.ref }}" == "refs/heads/preprod" ]; then
            git fetch origin preprod
            git checkout preprod
          elif [ "${{ github.ref }}" == "refs/heads/production" ]; then
            git fetch origin production
            git checkout production
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            git fetch origin main
            git checkout main
          else
            echo "Branch is not one of the predefined environments (dev, preprod, prod, main). Skipping build."
            exit 0
          fi

      - name: Build and tag Docker image
        run: |
          echo "Building Docker image for the ${{ github.ref }} environment..."
          
          # Determine the appropriate tags
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            IMAGE_TAG="dev"
            VERSION_TAG="dev-${GITHUB_SHA}"
          elif [ "${{ github.ref }}" == "refs/heads/preprod" ]; then
            IMAGE_TAG="preprod"
            VERSION_TAG="preprod-${GITHUB_SHA}"
          elif [ "${{ github.ref }}" == "refs/heads/production" ]; then
            IMAGE_TAG="prod"
            VERSION_TAG="prod-${GITHUB_SHA}"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            IMAGE_TAG="main"
            VERSION_TAG="main-${GITHUB_SHA}"
          else
            echo "Branch is not one of the predefined environments (dev, preprod, prod, main). Skipping build."
            exit 0
          fi
          
          # Build the Docker image
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:$IMAGE_TAG -t ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:$VERSION_TAG .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image to GitHub Container Registry..."
          docker push ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:$IMAGE_TAG
          docker push ${{ secrets.REGISTRY_URL }}/${{ github.repository }}:$VERSION_TAG
