name: Build and Publish Docker Image

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to External Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        run: |
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "TAG=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ env.TAG }}"

  trigger-terraform:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Terraform Workflow in Other Repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
               https://api.github.com/repos/my-org/terraform/actions/workflows/update-tfvars.yml/dispatches \
               -d '{"ref":"main","inputs":{"image_tag":"${{ env.TAG }}"}}'
