name: Create and publish a Docker image

on:
  push:
    branches: ['main', 'dev', 'preprod','production']
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1  # Enable BuildKit for efficient builds

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # Set up QEMU for multi-platform builds (amd64, arm64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        run: |
          # Get the short SHA (first 7 characters)
          SHORT_SHA=${{ github.sha }}
          SHORT_SHA=${SHORT_SHA:0:7}  # Extract the first 7 characters of the SHA

          # Get the branch name
          BRANCH_NAME=${{ github.ref_name }}
          
          if [[ "$BRANCH_NAME" == "dev" ]]; then
            IMAGE_TAG="dev"
            VERSION_TAG="dev-${SHORT_SHA}"
          elif [[ "$BRANCH_NAME" == "preprod" ]]; then
            IMAGE_TAG="preprod"
            VERSION_TAG="preprod-${SHORT_SHA}"
          elif [[ "$BRANCH_NAME" == "prod" ]]; then
            IMAGE_TAG="prod"
            VERSION_TAG="prod-${SHORT_SHA}"
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            IMAGE_TAG="main"
            VERSION_TAG="main-${SHORT_SHA}"
          else
            echo "Branch is not one of the predefined environments (dev, preprod, prod, main). Skipping build."
            exit 0
          fi          

          # Output the tags and labels for later use
          echo "::set-output name=tags::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION_TAG}"
          echo "::set-output name=labels::branch=${BRANCH_TAG},sha=${SHORT_SHA}"

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Build and push Docker image for multiple architectures (amd64, arm64)
      - name: Build and push Docker image for multiple architectures
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
